// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPlant1MoistureThresholdChange();
void onPlant1WaterLoadChange();
void onUnitsChange();
void onModule1SwitchChange();

int plant_1_Moisture_Threshold;
int plant_1_Water_Load;
int units;
bool module_1_Switch;

void initProperties(){

  ArduinoCloud.addProperty(plant_1_Moisture_Threshold, READWRITE, ON_CHANGE, onPlant1MoistureThresholdChange);
  ArduinoCloud.addProperty(plant_1_Water_Load, READWRITE, ON_CHANGE, onPlant1WaterLoadChange);
  ArduinoCloud.addProperty(units, READWRITE, ON_CHANGE, onUnitsChange);
  ArduinoCloud.addProperty(module_1_Switch, READWRITE, ON_CHANGE, onModule1SwitchChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
